config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
  resources :articles
  resources :users, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  attr_reader :author

  include PgSearch::Model
  pg_search_scope :search_by_title_text_author,
    against: [:title, :text],
    associated_against: {
    user: [:name, :surname]
    },
    using: {
      tsearch: { prefix: true }
    }

  def self.search(search)
      if search
          where("surname ILIKE ?", "%#{search}%").or(where("name ILIKE? ", "%#{search}%")).or(where("title ILIKE ?", "%#{search}%")).or(where("text ILIKE ?", "%#{search}%"))
          # Article.joins(:user).where("surname ILIKE ?", "%#{search}%")
      else
        all
      end
  end

  def author
      @name = User.find(self.user_id).name
      @surname = User.find(self.user_id).surname
      return "#{@name} #{@surname}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :articles, dependent: :destroy

  def self.options_for_select
    users = User.arel_table
    order("LOWER(name)").map { |e| [e.name, e.surname, e.id] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:surname, :name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:surname, :name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    @articles = policy_scope(Article)
    @q = Article.ransack(params[:q])
    @articles = @q.result.includes(:user).page(params[:page]).paginate(:per_page => 5, :page => params[:page])
  end

  def show
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize @article
    if @article.save
      redirect_to @article, notice: 'Shared successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to dashboard_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :user_id, :photo, :url)
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end

  # def sort_column
  #   Article.joins(:user).column_names.include?(params[:sort]) ? params[:sort] : "title"
  #   # Article.joins(:user).column_names.include?(params[:sort]) ? params[:sort] : "title"
  # end

  # def sort_direction
  #   %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:home]

    def home
        @article1 = sample
        @article2 = sample
        @article3 = sample

        if params[:query].present?
          @articles = Article.search_by_title_text_author(params[:query])
        else
          @articles = Article.all.limit(7)
        end
    end

    def dashboard
        @user = current_user
    end
    private

    def sample
        Article.all.sample
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :find_user, only: [ :show ]
  def show
    @courses = @user.courses
  end


  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, header = nil)
    header ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to header, request.params.merge({sort: column, direction: direction, page: nil}), {class: css_class }
    # Article.joins(:user).order(surname: :asc)
  end
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 m-2">
      <%= simple_form_for [ @article ] do |f| %>
        <%= f.input :photo, as: :file %>
        <%= f.input :title, label: 'Title' %>
        <%= f.input :text, label: "Whacha think?" %>
        <%= f.input :url, label: "URL" %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="articles-container">


<%= search_form_for @q do |f| %>
    <div class="field">
        <%= f.search_field :title_or_text_or_user_surname_cont %> <%= f.submit "Search" %>
    </div>
    <div class="counter m-2">
      <p> Found <strong><%= @articles.count %></strong> results </p>

    </div>
<% end %>

  <div class="index-container">
    <table class="pretty">
      <tr>
        <th><%= sort_link @q, :title, "Title" %></th>
        <th><%= sort_link(@q, :user_surname, 'Surname') %></th>
        <th><%= sort_link @q, :created_at, "Created" %></th>
        <th><%= sort_link @q, :updated_at, "Updated" %></th>
      </tr>
      <%  @articles.each do |article|  %>
            <tr>
                <td><%= link_to article_path(article) do %> <%= truncate(article.title, :length => 50) %> <% end %></td>
                <td><%= article.user.surname %></td>
                <td><%= article.created_at.strftime("%B %e, %Y") %></td>
                <td><%= article.updated_at.strftime("%B %e, %Y") %></td>
            </tr>
      <% end %>
    </table>
  </div>
   <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="container">

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @article.photo.key %>)">
  <h1><%= @article.title %></h1>
</div>

  <div class="row justify-content-center">
    <div class="col-8 m-2">
      <div class="ava-n-title">
        <div class="ava">
              <%= cl_image_tag @article.user.photo.key, class: "avatar-large" %>
        </div>
        <div class="title">
            <h2>Author: <%= @article.author%></h2>
        </div>
      </div>
      <p> <%= @article.text.gsub(/\[.*\]/, "") %></p>
      <% if @article.url? %>
        <p> <%= link_to 'Read More', @article.url %></p>
      <% end %>
      <p> <% if policy(@article).edit? %><%= link_to edit_article_path(@article) do %><i class="far fa-edit"></i> <% end %><% end %>
          <% if policy(@article).destroy? %><%= link_to article_path(@article), method: :delete, data: { confirm: "Are you sure you would like to delete?" } do %> <i class="far fa-trash-alt"></i> <% end %><% end %></p>

      <p>Created at: <%= @article.created_at%> || Last Updated: <%= @article.updated_at%></p>
      <p> </p>
      <p><%= link_to "Write an article", new_article_path, class: "btn btn-ghost" %>
        <%= link_to "Read Other Articles", articles_path, class: "btn btn-gradient" %> </p>
    </div>
  </div>
</div>

app/views/articles/trialtest.html.erb
<!-- INDEX.HTML.ERB -->
<div class="articles-container">

<%= form_tag articles_path, :method => 'get' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
        <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :title => nil %>
        </p>
<% end %>
<div class="index-container">
    <table class="pretty">
        <th> <%= sortable "title", "Sort By: Title" %> </th>
        <th class="author"> <%= sortable "user_id", "Author" %></th>
        <th> <%= sortable "created_at", "Created" %></th>
        <th><%= sortable "updated_at", "Updated" %></th>
        <% for article in @articles %>
            <tr>
                <td><%= link_to article_path(article) do %> <%= truncate(article.title, :length => 50) %> <% end %></td>
                <td><%= article.user.surname %></td>
                <td><%= article.created_at.strftime("%B %e, %Y") %></td>
                <td><%= article.updated_at.strftime("%B %e, %Y") %></td>
            </tr>
        <% end %>
    </table>
</div>
<%= @articles.count %>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAppMikamai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
    <div class="dashboard d-flex">
        <div class="col-4 m-2">
          <h1> Welcome <%= current_user.name.split(" ").first.capitalize %>,</h1>
          <!-- <h1>Pages#home</h1> -->
          <p> This is your dashboard</p>
          <p>Name: <%= current_user.name.split(" ").first.capitalize %> <%= current_user.surname.split(" ").first.capitalize %></p>
          <p>Email: <%= current_user.email %></p>
          <%= link_to "Write an article", new_article_path, class: "btn btn-ghost" %>
        </div>
        <div class="col-8 m-2">
          <h2>Your list of Articles:</h2> <% current_user.articles.each do |article| %>
              <p><%= link_to article.title, article_path(article) %>  <%= link_to edit_article_path(article) do %><i class="far fa-edit"></i> <% end %>
                <%= link_to article_path(article), method: :delete, data: { confirm: "Are you sure?" } do %> <i class="far fa-trash-alt"></i> <% end %>
              </p>
          <% end %>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="carousel-container">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
          <%= cl_image_tag @article1.photo.key, class: "image-carousel d-block w-100", alt: "First slide" %>
        <div class="carousel-caption d-none d-md-block">
          <h1> <%= link_to @article1.title, article_path(@article1) %></h1>
          <p><%= @article1.author %></p>
        </div>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag @article2.photo.key, class: "image-carousel d-block w-100", alt: "Second slide" %>
        <div class="carousel-caption d-none d-md-block">
          <h1><%= link_to @article2.title, article_path(@article2) %></h1>
          <p><%= @article2.author %></p>
        </div>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag @article3.photo.key, class: "image-carousel d-block w-100", alt: "Third slide" %>
        <div class="carousel-caption d-none d-md-block">
          <h1><%= link_to @article3.title, article_path(@article3) %></h1>
          <p><%= @article3.author %></p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div id="home-page" class="col-6 m-2">
    <h1>Atlas</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>

    <% if !user_signed_in? %>
      <p><%= link_to "Login", new_user_session_path, class: "btn btn-gradient" %>  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-signup"%></p>
    <% end %>
    </div>
  </div>
</div>



<div class="container">
  <div class="row">
    <div class="col-12 m-2">
      <div class="srch-bar">
        <%= form_tag root_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for an article"
          %>
          <p><%= submit_tag "Search", class: "btn btn-primary m-2" %></p>
        <% end %>
      </div>

<% @articles.each do |article| %>
      <div class="cards">
        <%= link_to article_path(article) do %>
            <div class="single-crd">
                <%= cl_image_tag article.photo.key, class: "picture" %>
              <div class="single-crd-infos">
                  <h4><%= link_to article.title, article_path(article) %></h4>
                  <p> <%= article.text.gsub(/\[.*\]/, "") %></p>
                  <p><%= article.author %></p>
              </div>
        <% end %>
            </div>
  <% end %>
      </div>
      <%= link_to "More Articles", articles_path, class: "btn btn-gradient" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="fas fa-globe-africa fa-2x"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Write an Article", new_article_path, class: "dropdown-item" %>
            <%= link_to "Read Articles", articles_path, class: "dropdown-item" %>
            <%= link_to 'Edit Your Account', edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Delete Account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>